name: facturi_app
description: "Aplicația Factura Locală este o soluție simplă și eficientă pentru generarea de facturi direct de pe telefon sau desktop, fără a necesita o conexiune la internet sau un server extern."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: 0.19.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  pdf: ^3.8.0
  printing: ^5.9.0
  share_plus: ^10.0.3
  cross_file: ^0.3.3
  flutter_pdfview: ^1.3.4
  url_launcher: ^6.1.10
  universal_platform: ^1.0.0+1
  csv: ^5.0.1
  archive: ^3.3.0
  image_picker: ^0.8.4+4
  sqflite_common_ffi: any
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  share_plus: 10.0.3
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf


